AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Transforms eml to markdown
Resources:
  transform:
    Type: AWS::Serverless::Function
    Properties:
      Description: Transforms eml to markdown
      Handler: src/index.handler
      Runtime: nodejs6.10
      CodeUri: build/transform.zip
      MemorySize: 1536
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: sourceBucket
        - S3CrudPolicy:
            BucketName:
              Ref: destBucket
      Timeout: 300
      Events:
        upload:
          Type: S3
          Properties:
            Bucket:
              Ref: source
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          DEST_BUCKET:
            Ref: destBucket
          TRANSFORMATION:
            Ref: transformation
  source:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: sourceBucket
Parameters:
  sourceBucket:
    Type: String
    Description: Name of the S3 Bucket to read source eml from (must NOT exist prior to deployment)
  destBucket:
    Type: String
    Description: Name of the S3 Bucket to put transformed markdown into (must exist prior to deployment)
  transformation:
    Type: Number
    Description: transformation type, 1 to 25, not yet implemented 
    Default: 25
